# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Publish

on:
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOS: windows
      GOARCH: amd64 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get GoLang version
      run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version: "${{ env.GO_VERSION }}"

    - name: Install dependencies
      run: |
        go get .

    - name: Build project
      run: go build -o build/ -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProxySwitcher
        path: build/*

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ProxySwitcher
        path: '${{ github.workspace }}/artifacts/'

    - name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" \
          --title "Release ${{ github.ref_name }}" \
          '${{ github.workspace }}/artifacts/'
